version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - path: ./.env
        required: true

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: